# apiVersion: cluster.x-k8s.io/v1beta1
# kind: MachineDeployment
# metadata:
#   name: {{ .Values.name }}-talos-workers
# spec:
#   clusterName: {{ .Values.name }}
#   replicas: 0
#   selector:
#     matchLabels:
#       cluster.x-k8s.io/cluster-name: {{ .Values.name }}
#       cluster.x-k8s.io/control-plane: "false"
#   template:
#     spec:
#       clusterName: {{ .Values.name }}
#       metadata:
#         labels:
#           cluster.x-k8s.io/cluster-name: {{ .Values.name }}
#           cluster.x-k8s.io/control-plane: "false"
#       bootstrap:
#         configRef:
#           apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
#           kind: TalosConfig
#           name: {{ .Values.name }}-talos-worker-config
#       infrastructureRef:
#         apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
#         kind: ProxmoxMachineTemplate
#         name: proxmox-worker-template
