{{- range $endpoint := .Values.records }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ $endpoint.name }}
spec:
  endpoints:
  - dnsName: '{{ $endpoint.name }}.mobrockers.com'
    recordType: A
    targets:
    - {{ $endpoint.ip }}
---
{{- end }}
{{- range $endpoint := .Values.ingress }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ $endpoint.name }}
spec:
  endpoints:
  - dnsName: '{{ $endpoint.name }}.{{ $endpoint.zone }}.mobrockers.com'
    recordType: A
    targets:
    - {{ $endpoint.ip }}
---
{{- end }}
