apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "homeAssistant.fullname" . }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "homeAssistant.fullname" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "homeAssistant.fullname" . }}-role-binding
roleRef:
  kind: ClusterRole
  name: {{ template "homeAssistant.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "homeAssistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
