 node-problem-detector:
   resources: { }

   metrics:
     enabled: true
     serviceMonitor:
       enabled: true
     prometheusRule:
       enabled: true
       defaultRules:
         create: true
