apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ .Values.name }}-talos-control-plane
spec:
  replicas: 1
  version: {{ .Values.kubernetes.version }}
  controlPlaneConfig:
    controlplane:
      talosVersion: {{ .Values.talos.version }}
      generateType: controlplane
      hostname:
        source: MachineName
      strategicPatches:
      - | {{ (.Files.Get "talos-patches/cluster.yaml") | nindent 4 }}
      - | {{ (.Files.Get "talos-patches/control-plane-vip.yaml") | nindent 4 }}
      - | {{ (.Files.Get "talos-patches/machine.yaml") | nindent 4 }}
      - | {{ (.Files.Get "talos-patches/region-meijhorst.yaml") | nindent 4 }}
      - | {{ (.Files.Get "talos-patches/zone-embla.yaml") | nindent 4 }}
      infrastructureTemplate:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ProxmoxMachineTemplate
        name: {{ .Values.name }}-proxmox-control-plane-machine-template
