apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ .Values.name }}-talos-control-plane
spec:
  replicas: 1
  version: {{ .Values.kubernetes.version }}
  controlPlaneConfig:
    controlplane:
      talosVersion: {{ .Values.talos.version }}
      generateType: controlplane
      hostname:
        source: MachineName
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ProxmoxMachineTemplate
    name: {{ .Values.name }}-proxmox-control-plane-machine-template
