providers:
  core:
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.8.5
  infrastructure:
    proxmox:
      image:
        repository: ghcr.io/ionos-cloud/cluster-api-provider-proxmox
        tag: v0.5.1
  bootstrap:
    talos:
      image:
        repository: ghcr.io/siderolabs/cluster-api-talos-controller
        tag: v0.6.6
  controlPlane:
    talos:
      image:
        repository: ghcr.io/siderolabs/cluster-api-control-plane-talos-controller
        tag: v0.5.7
