providers:
  core:
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.8.5
  infrastructure:
    proxmox:
      image:
        repository: ghcr.io/ionos-cloud/cluster-api-provider-proxmox
        tag: v0.5.1
