authentik:
  global:
    revisionHistoryLimit: 0

  authentik:
    error_reporting:
      enabled: false
    postgresql:
      host: env://AUTHENTIK_DATA_RW_SERVICE_HOST
      name: file:///postgres-credentials/dbname
      user: file:///postgres-credentials/username
      password: file:///postgres-credentials/password

  server:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    ingress:
      enabled: true
      hosts:
        - authentik.mobrockers.com
      tls:
        - hosts:
          - authentik.mobrockers.com

    volumes:
      - name: postgres-credentials
        secret:
          secretName: authentik-data-app
    volumeMounts:
      - name: postgres-credentials
        mountPath: /postgres-credentials
        readOnly: true
    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          key: secretKey
          name: authentik-secret

  worker:
    volumes:
      - name: postgres-credentials
        secret:
          secretName: authentik-data-app
    volumeMounts:
      - name: postgres-credentials
        mountPath: /postgres-credentials
        readOnly: true

  redis:
    enabled: true
