apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: '{{ .Values.cluster.image.repository }}:{{ .Values.cluster.image.tag }}'
  revisionHistoryLimit: 0 
  replicantTemplate:
    spec:
      replicas: 0

  config:
    data: |
      listeners.tcp.default {
        enable = false
      }
      listeners.ws.default {
        enable = false
      }
      listeners.wss.default {
        enable = false
      }

      listeners.ssl.internal {
        bind = "0.0.0.0:8884"
        ssl_options {
          cacertfile = "/mounted/certs/ca/trust-bundle.pem"
          certfile = "/mounted/certs/mqtt-emqx-svc-tls/tls.crt"
          keyfile = "/mounted/certs/mqtt-emqx-svc-tls/tls.key" 
        }
      }

      listeners.ssl.external {
        bind = "0.0.0.0:8883"
        ssl_options {
          certfile = "/mounted/certs/mqtt-mobrockers-com/tls.crt"
          keyfile = "/mounted/certs/mqtt-mobrockers-com/tls.key" 
        }
      }

      authentication = [{
        mechanism = "password_based"
        backend = "built_in_database"
      }]
      authorization {
        no_match = "deny"
        deny_action = "disconnect"

        sources = [{
          type = "built_in_database"
        }]
      }

      mqtt {
        ignore_loop_deliver = false
        retain_available = true
        wildcard_subscription = true
        use_username_as_clientid = true
      }
      retainer {
        enable = true
        backend {
          type = "built_in_database"
          storage_type = "disc"
        }
      }

  coreTemplate:
    spec:
      replicas: 2
      volumeClaimTemplates:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      extraVolumes:
      - name: svc-cluster-local-bundle
        configMap:
          name: svc-cluster-local-bundle
      - name: mqtt-mobrockers-com-tls
        secret:
          secretName: mqtt-mobrockers-com-tls
      - name: mqtt-emqx-svc-tls
        secret:
          secretName: mqtt-emqx-svc-tls
      extraVolumeMounts:
      - name: svc-cluster-local-bundle
        mountPath: /mounted/certs/ca
      - name: mqtt-mobrockers-com-tls
        mountPath: /mounted/certs/mqtt-mobrockers-com
      - name: mqtt-emqx-svc-tls
        mountPath: /mounted/certs/mqtt-emqx-svc-tls
      - name: mqtt-mobrockers-com-tls
        mountPath: /mounted/cert

      tolerations:
      - key: essential
        operator: Exists

  listenersServiceTemplate:
    metadata:
      annotations:
        'external-dns.alpha.kubernetes.io/hostname': mqtt.mobrockers.com
        'io.cilium/lb-ipam-ips': 10.0.103.30
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
