apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-mobrockers-com-tls
spec:
  secretName: mqtt-mobrockers-com-tls
  dnsNames:
  - 'mqtt.mobrockers.com'
  issuerRef:
    name: cloudflare-letsencrypt-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-emqx-svc-tls
spec:
  secretName: mqtt-emqx-svc-tls
  dnsNames:
  - 'emqx-listeners.emqx.svc.cluster.local'
  issuerRef:
    name: svc-cluster-local-issuer
    kind: ClusterIssuer
