apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls-certificate
spec:
  secretName: mqtt-tls-certificate
  dnsNames:
  - 'mqtt.mobrockers.com'
  issuerRef:
    name: cloudflare-letsencrypt-dns
    kind: ClusterIssuer
