apiVersion: v2
name: cert-manager
version: 1.0.0

dependencies:
  - name: cert-manager
    version: v1.16.0
    repository: https://charts.jetstack.io
  - name: trust-manager
    version: v0.12.0
    repository: https://charts.jetstack.io
