apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: {{ .Values.providers.core.image.tag }}
  manager:
    featureGates:
      ClusterTopology: true
      MachinePool: true
