persistence:
  size: 1Ti
  storageClass: ''
  accessMode: ReadWriteMany

ingress:
  enabled: true
  domain: photos.mobrockers.com
  annotations:
    # proxy-body-size is set to 0 to remove the body limit on file uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    enabled: true

database:
  image:
    registry: ghcr.io
    repository: tensorchord/cloudnative-pgvecto.rs
    tag: 16.3

  replicas: 2
  size: 32Gi
  backups:
    enabled: false

machineLearning:
  replicas: 1
  image:
    registry: ghcr.io
    repository: immich-app/immich-machine-learning
    tag: v1.106.3
    pullPolicy: IfNotPresent

server:
  replicas: 1
  image:
    registry: ghcr.io
    repository: immich-app/immich-server
    tag: v1.106.2
    pullPolicy: IfNotPresent

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
