cluster:
  clusterName: embla
  controlPlane:
    endpoint: https://10.0.254.254:6443
  
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0

  scheduler:
    extraArgs:
      bind-address: 0.0.0.0

  network:
    cni:
      name: none
  proxy:
    disabled: true

  discovery:
    enabled: false
  