apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
    - name: http
      port: 32400
      targetPort: http
    - name: tautulli-http
      port: 8181
      targetPort: tautulli-http
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
