apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.infro.config.existingSecretName }}
spec:
  encryptedData: {{ toYaml .Values.infro.config.sealedValues | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.infro.config.existingSecretName }}
