recordSets:
  - name: embla
    ip: 10.0.10.10
  - name: truenas
    ip: 10.0.10.100
  - name: k8s
    ip: 10.0.10.110
  - name: work-laptop-rouke
    ip: 10.0.20.161

external-dns:
  crd:
    create: true
  revisionHistoryLimit: 0

  policy: sync
  sources:
    - ingress
    - service
    - crd

  provider: webhook

  extraArgs:
    webhook-provider-url: http://localhost:8888

  sidecars:
  - name: adguard-webhook
    image: ghcr.io/muhlba91/external-dns-provider-adguard:v5.1.0
    ports:
    - containerPort: 8888
      name: http
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
    - name: LOG_LEVEL
      value: debug
    - name: ADGUARD_URL
      value: http://adguard-primary.adguard:3000
    - name: ADGUARD_USER
      value: "admin"
    - name: ADGUARD_PASSWORD
      value: nyDRXHM@$rc#wqAojVWn8qW6!o#4aq!d9d6BPLjL42fSoY3j@q3#sezQcAy3XtLB
    - name: SERVER_HOST
      value: "0.0.0.0" 
    - name: DRY_RUN
      value: "false"

  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 30Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
