external-dns:
  crd:
    create: true
  revisionHistoryLimit: 0

  policy: sync
  sources:
    - ingress
    - service
    - crd

  provider: webhook

  extraArgs:
    webhook-provider-url: http://localhost:8888

  sidecars:
  - name: adguard-webhook
    image: ghcr.io/muhlba91/external-dns-provider-adguard:v6.0.0
    ports:
    - containerPort: 8888
      name: http
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
    - name: LOG_LEVEL
      value: debug
    - name: ADGUARD_URL
      value: http://adguard-web.adguard:3000
    - name: ADGUARD_USER
      value: "admin"
    - name: ADGUARD_PASSWORD
      valueFrom:
        secretKeyRef:
          name: adguard-credentials
          key: password
    - name: SERVER_HOST
      value: "0.0.0.0" 
    - name: DRY_RUN
      value: "false"

  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 30Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
