apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: {{ .Values.name }}-proxmox-cluster
spec:
  credentialsRef:
    name: proxmox-credentials
  allowedNodes: [{{ .Values.name }}]
  controlPlaneEndpoint:
    host: 10.0.254.254
    port: 6443
  dnsServers: [10.0.254.1]
  ipv4Config:
    gateway: 10.0.254.1
    prefix: 24
    addresses:
    - 10.0.254.20-10.0.254.200
