home-assistant:

  podSecurityContext:
    fsGroup: 5000

  securityContext:
    runAsGroup: 5000
    capabilities: {}

  persistence:
    size: 500Mi

  ingress:
    enabled: true
    class: nginx
    domain: home.mobrockers.com
    tls:
      enabled: true

  config:
    securityContext:
      runAsGroup: 5000

matterHub:
  image:
    repository: ghcr.io/t0bst4r/home-assistant-matter-hub
    tag: 3.0.0-alpha.41
