apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-media
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  capacity:
    storage: 1Ti
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 90ad01be-ee8b-480c-96ec-6fd31340b645
    volumeAttributes:
      server: truenas.mobrockers.com
      share: /mnt/slow/media
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media
spec:
  storageClassName: ""
  volumeName: sabnzbd-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
