apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
      app.kubernetes.io/instance: sabnzbd
  endpoints:
    - port: metrics
      interval: 60m
      scrapeTimeout: 5m
      path: /metrics
