apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9707
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
