apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gatus-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gatus-role-binding
roleRef:
  kind: Role
  name: gatus-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gatus
  namespace: {{ .Release.Namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatus-cluster-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gatus-cluster-role-binding
roleRef:
  kind: Role
  name: gatus-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gatus
  namespace: {{ .Release.Namespace }}
