spegel:
  revisionHistoryLimit: 0

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  podSecurityContext:
    fsGroup: 2000

  spegel:
    logLevel: "WARN"
    ontainerdRegistryConfigPath: /etc/cri/conf.d/hosts
    
  serviceMonitor:
    enabled: true

  grafanaDashboard:
    enabled: true

