image:
  registry: docker.io
  repository: adguard/adguardhome
  tag: v0.107.51

primary:
  resources: {}

secondary:
  replicas: 2
  resources: {}

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: adguard-secondary
          app.kubernetes.io/instance: adguard
          app.kubernetes.io/name: adguard

persistence:
  size: 1Gi

service:
  annotations:
    'io.cilium/lb-ipam-ips': 10.0.10.250

ingress:
  enabled: true
  domain: adguard.mobrockers.com
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://adguard.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |-
      proxy_set_header X-Forwarded-Host $http_host;
  tls:
    enabled: true

sync:
  resources: {}

  config:
    password: nyDRXHM@$rc#wqAojVWn8qW6!o#4aq!d9d6BPLjL42fSoY3j@q3#sezQcAy3XtLB
    loglevel: info
    cron: "*/1 * * * *"

  image:
    registry: ghcr.io
    repository: bakito/adguardhome-sync
    tag: v0.6.11
