apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: buildarr
      app.kubernetes.io/name: buildarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: buildarr
        app.kubernetes.io/name: buildarr 
    spec:
      automountServiceAccountToken: false
      containers:
        - name: buildarr
          image: '{{ .Values.buildarr.image.repository }}:{{ .Values.buildarr.image.tag }}'
          env:
            - name: TZ
              value: TZ=Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          volumeMounts:
            - name: secrets-cache
              mountPath: /secrets
            - name: buildarr-config
              mountPath: /config
            - name: prowlarr-config
              mountPath: /prowlarr
            - name: prowlarr-api-key
              mountPath: /prowlarr/secrets
            - name: drunken-slug-api-key
              mountPath: /drunken-slug/secrets
            - name: nzbfinder-api-key
              mountPath: /nzbfinder/secrets
            - name: nzbgeek-api-key
              mountPath: /nzbgeek/secrets
            - name: sonarr-config
              mountPath: /sonarr
            - name: sonarr-api-key
              mountPath: /sonarr/secrets
            - name: radarr-config
              mountPath: /radarr
            - name: radarr-api-key
              mountPath: /radarr/secrets
      volumes:
        - name: secrets-cache
          emptyDir:
            sizeLimit: 10Mi
        - name: buildarr-config
          configMap:
            name: buildarr-config
        - name: prowlarr-config
          configMap:
            name: prowlarr-config
        - name: prowlarr-api-key
          secret:
            secretName: prowlarr-api-key
        - name: drunken-slug-api-key
          secret:
            secretName: drunken-slug-api-key
        - name: nzbfinder-api-key
          secret:
            secretName: nzbfinder-api-key
        - name: nzbgeek-api-key
          secret:
            secretName: nzbgeek-api-key
        - name: sonarr-config
          configMap:
            name: sonarr-config
        - name: sonarr-api-key
          secret:
            secretName: sonarr-api-key
        - name: radarr-config
          configMap:
            name: radarr-config
        - name: radarr-api-key
          secret:
            secretName: radarr-api-key
