apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
  endpoints:
    - port: metrics
      interval: 60m
      scrapeTimeout: 5m
      path: /metrics
