apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "common.fullname" . }}-library
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "immich"
    {{- include "common.labels" . | nindent 4 }}
spec:
  claimRef:
    name: {{ template "common.fullname" . }}-library
    namespace: {{ .Release.Namespace }}
  accessModes:
    - {{ .Values.immich.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  capacity:
    storage: {{ .Values.immich.persistence.size }}
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 62c123a8-b303-4470-a092-2fb098798c5f
    volumeAttributes:
      server: truenas.mobrockers.com
      share: /mnt/slow/photos
      node_attach_driver: nfs
      provisioner_driver: node-manual

