apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-credentials
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: {{ .Values.credentialsSealed | toYaml | nindent 6 }}
