descheduler:
  kind: Deployment
  deschedulingInterval: 5m
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  deschedulerPolicy:
    profiles:
    - name: DefaultEvictor
      nodeFit: true
      evictLocalStoragePods: true
      evictFailedBarePods: true
    - name: PodLifeTime
      args:
        maxPodLifeTimeSeconds: 120
        states:
        - Unknown
        - Pending
        - NodeAffinity
        - NodeLost
        - Shutdown
        - UnexpectedAdmissionError
    - name: RemovePodsHavingTooManyRestarts
      args:
        podRestartThreshold: 10
        includingInitContainers: true
    - name: LowNodeUtilization
      args:
        thresholds:
          cpu : 20
          memory: 20
        targetThresholds:
          cpu : 50
          memory: 50
    - name: RemovePodsViolatingNodeAffinity
      args:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
        - preferreddDuringSchedulingIgnoredDuringExecution
    - name: RemovePodsViolatingInterPodAntiAffinity
    - name: RemovePodsViolatingTopologySpreadConstraint
      args:
        topologyBalanceNodeFit: true
        constraints:
        - DoNotSchedule
        - ScheduleAnyway
    - name: RemovePodsViolatingNodeTaints
      args:
        includePreferNoSchedule: true
        excludedTains:
        - node.kubernetes.io/unschedulable
    plugins:
      deschedule:
        enabled:
        - PodLifeTime
        - RemovePodsHavingTooManyRestarts
        - RemovePodsViolatingInterPodAntiAffinity
        - RemovePodsViolatingNodeAffinity
        - RemovePodsViolatingNodeTaints
      balance:
        enabled:
        - LowNodeUtilization
        - RemovePodsViolatingTopologySpreadConstraint
