replicas: 1

image:
  registry: ghcr.io
  repository: home-assistant/home-assistant
  tag: 2024.4.4

resources: {}

deploymentStrategy:
  type: Recreate

podSecurityContext:
  fsGroup: 5000

securityContext:
  allowPrivilegeEscalation: false
  runAsGroup: 5000
  # capabilities:
  #   drop: [ "ALL" ]
  #   add: ["NET_RAW", "NET_BIND_SERVICE"]

persistence:
  accessMode: ReadWriteOnce
  size: 500Mi

ingress:
  enabled: true
  domain: home.mobrockers.com
  tls:
    enabled: true

config:
  # secret:
  #   name: home-assistant-secret
  #   sealedValues:
  #     secretsYaml: 

  image:
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.26.1
