home-assistant:

  podSecurityContext:
    fsGroup: 5000

  securityContext:
    runAsGroup: 5000
    capabilities:
      add: []

  persistence:
    size: 500Mi

  ingress:
    enabled: true
    class: nginx
    domain: home.mobrockers.com
    tls:
      enabled: true

  config:
    securityContext:
      runAsGroup: 5000
