apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mealie-data-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": mealie-data
  podMetricsEndpoints:
  - port: metrics
