apiVersion: apps/v1
kind: Deployment
metadata:
  name: truecommand
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: truecommand
      app.kubernetes.io/name: truecommand
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: truecommand
        app.kubernetes.io/name: truecommand 
    spec:
      automountServiceAccountToken: false
      containers:
        - name: truecommand
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: truecommand-data
