records:
- name: vpn
  ip: 31.187.194.110
- name: embla
  ip: 10.0.100.10
- name: truenas
  ip: 10.0.101.10
- name: k8s
  ip: 10.0.102.10
- name: work.rouke
  ip: 10.0.50.230

ingress:
- name: robin
  auth: true
  ip: 10.0.30.45
