apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-wildcard-certificate
spec:
  secretName: default-wildcard-certificate
  dnsNames:
  - 'mobrockers.com'
  - '*.mobrockers.com'
  issuerRef:
    name: cloudflare-letsencrypt-dns
    kind: ClusterIssuer
