apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "kube-prometheus-stack" "prometheus-node-exporter" "namespaceOverride" }}
  labels:
    pod-security.kubernetes.io/enforce: 'privileged'
