apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      containers:
      - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        args:
        - --domain 
        - device.local
        - --log-level
        - all
        # - --device
        # - |
        #   name: temp
        #   groups:
        #   - paths:
        #     - path: /dev/ttyUSB*
        #   - paths:
        #     - path: /dev/ttyACM*
        - --config 
        - /config/config.yaml
        name: generic-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 20Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: config
          mountPath: /config
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: config
        configMap:
          name: devices
      tolerations:
      - operator: Exists
  updateStrategy:
    type: RollingUpdate
