apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  exec.enabled: 'true'
  url: https://argocd.mobrockers.com
  statusbadge.enabled: 'false'
  users.anonymous.enabled: 'false'

  oidc.config: |
    name: Authentik
    issuer: https://authentik.mobrockers.com/application/o/argocd/
    logoutURL: https://authentik.mobrockers.com/application/o/argocd/end-session/
    clientID: $authentik-credentials:client_id
    clientSecret: $authentik-credentials:client_secret
    requestedScopes: ['openid', 'profile', 'email', 'groups', 'offline_access']
  accounts.infro: apiKey
