democratic-csi:

  csiDriver:
    name: "org.democratic-csi.nfs.hdd"

  storageClasses:
  - name: truenas-nfs-hdd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "nfs"

    mountOptions:
    - noatime
    - nfsvers=4

    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-hdd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: AgBoG8tjSGasDOZH9sljSFkwyttjQrbM+wpdgYMGS1Bw3CRekiCosSEyuz03HlmUFJgswWXctTRmZvV1D8i2WCshCqZaflqP8UCHCqe+ESTlOwDLLoG5fTztXSIsWAiGtzQexiIs/eJyFWQL12W9TJgyuYXfQKHj/gokWr23CcwMGeJUEyVEK/KI0bBVIr8BcryQ6Rxsge/SI3fQX6JN5qKvqYoiAwcaxqmbE60Jh9IuxO8+EYMiiPg68uSZHAE2hPY6KGGqidlr+jGVC6B7YLwMSDkuoyrrFKLx0GUPRJTYvC79/p5U4EK+qWKVsrX4xtUAr7lSViAOKuQBhudW1vDB+w8JJwUKEkuuoS/ch53jGGc+D2r/j1WuFJ//mzMe0ph6jKpZ1W+5pnDDepvKPFjnpRG2nLn1Xf7+VOskqG1fpiQBkTcuvbTomgokgmS7V2h0zzk/cqOzQYWPPstCNuhbyoWaFEplROsJZNvl3+mptmgbKRCcP1nW7cUxIjxJY3UrqO+k6EukwsuyAtpwRST0vkEKUav86Yh7yyqamxjLfUTz6J6eQsAsk9OwpRAM9joJt5bt3UfDWqhwCSU28fcDguhedZ+p4wJ3CEfO91sGYMsPelANb7ZWNDGke5Z8D1NY/ey4PSx46+nP8sNPTLS05WLnWQ6is5hqcu9UJBWym8GvK9AzFfE8vY+QeyAE5mia+b91wK/YKAlVjL0vuCoWCWrAhDSe39OswboWyDQ7nhmuJX/8KlXXflnh8d/+oNnX/L1hXHurcLa/lgkr4UVL4J+ZoEZNFUQAHrmyfEBwtJs79YU5InSOGI3eVcs33wwmUFQbsgpkpCcHxwWbm60IO6Agsb2YE72jQVhODNz3eMj+hLohza/JK05lGeu77tyUxR1c7NoB4jFgshcmh9EmlS7d8C7ilHlOesPcBTMw/HXOhNl3oC4HoNhwgFduwo3mmwc0YSS1CTpr16RWCXwyTe3CNpUadA9y/ZNvC1IvHYGft0Pt0Bdi17gtbrbmW/6yNpkx88bclUzaP55vHIzfKh5LL1OdsShlX9kGUUArs5KbbIa/7TIECJxOiS/a7HqxSSW1Ck5ix/dBXnedkhguGvOBu4DWNhJlLN1PFKj8f+js3Gzg7p9njBrb/Z5bJTq/1VGSTOza3IzYVcDuuvz6I/miCbGXAp5OIgz87y3GCnH806m1XoH2c5bpsvSBMgH3qXSgga7lCetL1svQOJr3Jcd7LSrQ+RNOCNOIY1QVaZucWqqNDalx4QyiDF4BQfw8nrQnER2bMfmhmMd01lGp5GXmwnLlP75YQEbMN7rjiZCcN6+rNWsZxyX3nGK1L88ytkhGHi1fZ/JYAVCQqX9KSCrWUJ27nhumKlhhWJzbUm5wsp0Yah7qEcu5uVhwGaKSkvNP1xa/dGVwp6vyeFpO2m0Czxndvj5csyYGK7z5fGqsrTyk+fmSVp6EEMyQL7lB6MQnacVHT/skc4v7q9mo9h5Or571Z0gKSN/lG4ZOQTWkaUWfXoOzcpWCxBlqYlkdLuZOzkXvNzoKLQWNgEPkFjxiHki2B1yoTBbFPLtL8O+RFvM9mWrjaa+hgllDCVZCFop8ZIvZybKxpwMm5a4RcwBnXET3JK7P9aKfLfH8Pv1Sisy7N51+Ysgz39tTZTtCoYNymnp2NHCB3MIOpkMf0sk5gnXVkw5NoO2N1mEsoC1GtQ5cqHReRCWism6JEuaDywu79MVHaF1GTr6jbj1ZRwMqLGXacZe19dzdmQ3t9OlsokqjfVFWh6RYmcjPZD+pMCls418a+o0UVGJGo23V7McQVjdoPmgpkcA1h8PWdk2c2h5WM1yMc77hhiv04KdV+xPg1zmoQbP3DOYpq4koH/ci8OZ0Qh45MddPLCJfc0/82VRG2pYmdab9aPy3z4O59BUFTK/qzSfbPVam22Zz6cOcSn2KN5BG8eeQCg59pCL+g9NFCF+BTTTQUk7+aGFOMn9YJyJ/ybpqGic8xXF5Tb4hCOhugrgeSkAFFcQYyo3xTb8IgR/dPMcvqgBVvVFM0fhLT+lwZDhOxPZ7DkS1kKA0OY/O+ZBSmSK8