apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-hdd-config
  namespace: democratic-csi-iscsi-hdd
stringData:
  driver-config-file.yaml: |-
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-api-iscsi
    node:
      mount:
        checkFilesystem:
          ext4:
            enabled: true
    instance_id:
    httpConnection:
      protocol: https
      host: truenas.mobrockers.com
      port: 443
      apiKey: 
      allowInsecure: false
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: slow/k8s/iscsi/v
      detachedSnapshotsDatasetParentName: slow/k8s/iscsi/s
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      zvolEnableReservation: false
    iscsi:
      targetPortal: "truenas.mobrockers.com:3260"
      extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      nameTemplate: "{{ name }}"
      namePrefix: "csi-"
      nameSuffix: "-k8s"
      # add as many as needed
      targetGroups:
          # get the correct ID from the websocket messages because the actual id might be different from the UI index
        - targetGroupPortalGroup: 3
          # get the correct ID from the websocket messages because the actual id might be different from the UI index
          targetGroupInitiatorGroup: 3
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the websocket messages because the actual id might be different from the UI index
          # only required if using Chap
          targetGroupAuthGroup:

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: SSD
      extentAvailThreshold: 80
      