apiVersion: v1
kind: Secret
metadata:
  name: truenas-nfs-hdd-config
  namespace: democratic-csi-nfs-hdd
stringData:
  driver-config-file.yaml: |-
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: https
      host: truenas.mobrockers.com
      port: 443
      apiKey: 
      allowInsecure: false
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: slow/k8s/nfs/v
      detachedSnapshotsDatasetParentName: slow/k8s/nfs/s
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: truenas.mobrockers.com
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""
