apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC43B18rY4SKicCTXWVYa7U0N9qyP9fd/SkNXqdqZQl/Lewn1rAoM1ZVeaHgSKYBLPSUsYpEoibBPTkVXClsLa/ZPfDm44HXUJb3ehMhTLq06pr8zXqTTw3zDP5DTAoXzuXN5h8/PWsFVDpIfvJ90RqNB316JtYqpL5/YdRYejmyDgMJjoNJCZTIsmeltQgyEwkOcYfSn/MXsA+38FhWscJd9LpsMykAj6Us38ifyHkrPOYwoMmjIF4CmqwDJzdCCTqXPwz/DCEZhsQ/HWL0LWqg1ZJCbTZuE/xhlbSnjB6f138dMwog1JptegU5sgEnSLwMvHQgtU29cBTQzm01OIrx9dyIBF4RYGWgkU5KhQTpLvMxPBEuc3WQqQto0XeVS6ksLmJULRgNipVlJLCJg6cG14XgWRkTHFzSASX5Pv+ZGHQanzPEGeuxDqNWTw6CYC+woW5dwCXS53vKWOmUN/KE3O9p6Vdf9PvjDEPBChCpR6jJ6Vuj5054n5k0Pg+uDOh8rNeCytQRqlF/NogRqTGDpc1cKj1QXJxRfGozhpY65lFJhcRbYL37lBDYwWf9ucjHyXTgKDPg39ZcjGBC2LXcG34y0h5NA0Lfu5Hd58JAqA4Wpa7spbg46yu5UAbAqYKGPLeV4HvQRPNeYWPmKWBL992nUPThPmw9V2QG+8iUAV7cVjDU+CnZSUORyZoxSms4eKScvKjkQa+3qJjd3mgTRenLUq23pV2M4ho85wPIL2EW9X0fS2C
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
