apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: trust-manager-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: svc-cluster-local-ca
spec:
  isCA: true
  commonName: svc.cluster.local
  secretName: svc-cluster-local-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: trust-manager-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: svc-cluster-local-issuer
spec:
  ca:
    secretName: svc-cluster-local-ca-secret
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: svc-cluster-local-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: svc-cluster-local-ca-secret
      key: tls.crt
  target:
    configMap:
      key: trust-bundle.pem
