argo-cd:
  global:
    revisionHistoryLimit: 0

  dex:
    enabled: false
  applicationSet:
    enabled: false
  notifications:
    enabled: false

  configs:
    secret:
      createSecret: true
    cm:
      create: false
      exec.enabled: true
    rbac:
      create: false
    params:
      create: false

  controller:
    replicas: 1

  redis:
    enabled: true

  server:
    replicas: 1

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hostname: argocd.mobrockers.com
      extraTls:
      - hosts:
        - argocd.mobrockers.com

  repoServer:
    replicas: 1
